### ISSUE TITLE
Branch 1 uses outdated PreloadedSpriteSingle

### ISSUE THREAD

**Issue by Arkessler** [EngoEngine/TrafficManager#11]
This should be renamed to LoadedSprite

**Comment by ramirezp6856** [comment]
@Arkessler You're right! Thanks!

**Comment by giangm9** [comment]
You didn't rename it

**Comment by jrmiller82** [comment]
This bug is still here. Needs to be fixed.

**Comment by jrmiller82** [comment]
Just submitted three PRs that fix this in branches 1, 2, and 3.

**Comment by paked** [comment]
Sorry this took so long to fix everyone.

PRs merged in now :)
